#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  generate-tailscale-ssh-config.sh [options]

Options:
  --output PATH        Output file (default: ~/.ssh/config.tailscale)
  --user USER          SSH user for generated hosts (default: current user)
  --identity PATH      IdentityFile path (default: ~/.ssh/id_ed25519)
  --prefix PREFIX      Host alias prefix (default: ts-)
  --online-only        Include only peers currently online
  -h, --help           Show this help

Examples:
  scripts/generate-tailscale-ssh-config.sh
  scripts/generate-tailscale-ssh-config.sh --online-only
  scripts/generate-tailscale-ssh-config.sh --output ~/dotfiles/ssh/config.tailscale
EOF
}

output_file="${HOME}/.ssh/config.tailscale"
ssh_user="${USER}"
identity_file="${HOME}/.ssh/id_ed25519"
host_prefix="ts-"
online_only=0

while (($# > 0)); do
  case "$1" in
    --output)
      output_file="${2:-}"
      shift 2
      ;;
    --user)
      ssh_user="${2:-}"
      shift 2
      ;;
    --identity)
      identity_file="${2:-}"
      shift 2
      ;;
    --prefix)
      host_prefix="${2:-}"
      shift 2
      ;;
    --online-only)
      online_only=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$output_file" || -z "$ssh_user" || -z "$identity_file" ]]; then
  echo "Required option value is missing." >&2
  usage >&2
  exit 1
fi

if ! command -v tailscale >/dev/null 2>&1; then
  echo "tailscale CLI not found in PATH." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required to parse tailscale status JSON." >&2
  exit 1
fi

status_output="$(tailscale status --json 2>&1 || true)"
if ! printf '%s\n' "$status_output" | jq -e . >/dev/null 2>&1; then
  echo "Failed to read tailscale status JSON. Is Tailscale running and authenticated?" >&2
  echo "$status_output" >&2
  exit 1
fi
status_json="$status_output"

entries="$(
  printf '%s\n' "$status_json" | jq -r \
    --arg user "$ssh_user" \
    --arg identity "$identity_file" \
    --arg prefix "$host_prefix" \
    --argjson online_only "$online_only" '
      def clean_host:
        (sub("\\.$"; ""));

      def alias_for($host):
        ($host
        | ascii_downcase
        | gsub("[^a-z0-9_-]"; "-")
        | gsub("-+"; "-")
        | sub("^-"; "")
        | sub("-$"; ""));

      (.Peer // {})
      | to_entries
      | map(.value)
      | map(select((.TailscaleIPs // []) | length > 0))
      | map(select(($online_only == 0) or (.Online == true)))
      | sort_by(.DNSName // .HostName // .TailscaleIPs[0])
      | .[]
      | ((.DNSName // .HostName // .TailscaleIPs[0]) | clean_host) as $host
      | ($prefix + alias_for($host)) as $alias
      | [
          "Host \($alias) \($host)",
          "  HostName \($host)",
          "  User \($user)",
          "  IdentityFile \($identity)",
          "  IdentitiesOnly yes",
          ""
        ]
      | .[]
    '
)"

mkdir -p "$(dirname "$output_file")"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Generated by scripts/generate-tailscale-ssh-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: tailscale status --json"
  echo "# Do not edit manually."
  echo
  if [[ -n "$entries" ]]; then
    printf '%s\n' "$entries"
  else
    echo "# No Tailscale peers found."
  fi
} > "$tmp_file"

mv "$tmp_file" "$output_file"
chmod 600 "$output_file" 2>/dev/null || true
trap - EXIT

host_count="$(grep -c '^Host ' "$output_file" || true)"
echo "Wrote ${output_file} (${host_count} hosts)."
